export const SURVEY_QUESTIONS = [
  {
    key: "establishment_type",
    title: "Qual é o tipo do seu estabelecimento?",
    options: ["Restaurante", "Bar", "Doceria", "Lanchonete", "Cafeteria", "Outro"],
    multi: false,
    otherKey: "establishment_type_other",
    otherPlaceholder: "Qual tipo?",
    adminOtherTitle: 'Tipo de estabelecimento — respostas "Outro"',
  },
  {
    key: "units_count",
    title: "Quantas unidades você gerencia com o Bite Menu?",
    options: ["1", "2 a 5", "6 a 20", "Mais de 20"],
    multi: false,
  },
  {
    key: "main_uses",
    title: "Para que você mais usa o Bite Menu hoje? (pode escolher mais de uma)",
    options: [
      "Cardápio digital na mesa (QR code)",
      "Cardápio para delivery",
      "Receber pedidos pelo WhatsApp",
      "Cardápio para redes sociais",
      "Controle interno de produtos e preços",
      "Controle de pedidos e vendas",
    ],
    multi: true,
  },
  {
    key: "update_frequency",
    title: "Com que frequência você atualiza seu cardápio no Bite Menu?",
    options: ["Todo dia ou quase isso", "Uma vez por semana", "Raramente", "Nunca mexi desde que configurei"],
    multi: false,
  },
  {
    key: "improvements",
    title: "Desde que começou a usar o Bite Menu, o que melhorou no seu negócio? (pode escolher mais de uma)",
    options: [
      "Processo ficou mais organizado",
      "Clientes pedem com mais facilidade",
      "Reduzi custos com plataformas de delivery",
      "Passei uma imagem mais profissional",
      "Aumentei meu ticket médio",
      "Consegui vender mais",
      "Ainda não percebi diferença",
    ],
    multi: true,
  },
  {
    key: "has_referred",
    title: "Você já indicou o Bite Menu para alguém?",
    options: ["Sim, já indiquei", "Não, mas indicaria", "Não indicaria ainda"],
    multi: false,
  },
  {
    key: "referral_source",
    title: "Como você conheceu o Bite Menu?",
    options: [
      "Instagram",
      "Google / busca",
      "Indicação de amigo ou conhecido",
      "Vi outro estabelecimento usando",
      "YouTube",
      "Outro",
    ],
    multi: false,
    otherKey: "referral_source_other",
    otherPlaceholder: "Como conheceu?",
    adminOtherTitle: 'Como conheceu — respostas "Outro"',
  },
  {
    key: "previous_tool",
    title: "O que você usava antes do Bite Menu?",
    options: [
      "Não usava nada / cardápio físico (papel)",
      "Planilha ou caderno",
      "iFood",
      "Anota AI",
      "Goomer",
      "Outro cardápio digital",
      "Outro",
    ],
    multi: false,
    otherKey: "previous_tool_other",
    otherPlaceholder: "O que usava?",
    adminOtherTitle: 'O que usava antes — respostas "Outro"',
  },
  {
    key: "decision_factor",
    title: "O que mais te convenceu a assinar o Bite Menu?",
    options: [
      "Facilidade de uso",
      "Preço",
      "Design / aparência do cardápio",
      "Controle de pedidos/vendas",
      "Indicação / confiança em quem indicou",
      "Outro",
    ],
    multi: false,
    otherKey: "decision_factor_other",
    otherPlaceholder: "O que te convenceu?",
    adminOtherTitle: 'O que convenceu a assinar — respostas "Outro"',
  },
];
