// Lista de moedas suportadas. A escolha muda APENAS o símbolo exibido —
// não há conversão de valores. Real (BRL) sempre primeiro / padrão.

export const DEFAULT_CURRENCY = "BRL";

export const CURRENCIES = [
  { code: "BRL", symbol: "R$", label: "Real brasileiro (BRL)" },
  { code: "USD", symbol: "US$", label: "Dólar americano (USD)" },
  { code: "EUR", symbol: "€", label: "Euro (EUR)" },
  { code: "GBP", symbol: "£", label: "Libra esterlina (GBP)" },
  { code: "ARS", symbol: "AR$", label: "Peso argentino (ARS)" },
  { code: "CLP", symbol: "CLP$", label: "Peso chileno (CLP)" },
  { code: "COP", symbol: "COL$", label: "Peso colombiano (COP)" },
  { code: "MXN", symbol: "MX$", label: "Peso mexicano (MXN)" },
  { code: "PEN", symbol: "S/", label: "Sol peruano (PEN)" },
  { code: "UYU", symbol: "$U", label: "Peso uruguaio (UYU)" },
  { code: "PYG", symbol: "₲", label: "Guarani paraguaio (PYG)" },
  { code: "BOB", symbol: "Bs", label: "Boliviano (BOB)" },
  { code: "VES", symbol: "Bs.S", label: "Bolívar venezuelano (VES)" },
  { code: "CAD", symbol: "CA$", label: "Dólar canadense (CAD)" },
  { code: "AUD", symbol: "A$", label: "Dólar australiano (AUD)" },
  { code: "NZD", symbol: "NZ$", label: "Dólar neozelandês (NZD)" },
  { code: "CHF", symbol: "CHF", label: "Franco suíço (CHF)" },
  { code: "JPY", symbol: "¥", label: "Iene japonês (JPY)" },
  { code: "CNY", symbol: "CN¥", label: "Yuan chinês (CNY)" },
  { code: "INR", symbol: "₹", label: "Rúpia indiana (INR)" },
  { code: "KRW", symbol: "₩", label: "Won sul-coreano (KRW)" },
  { code: "VND", symbol: "₫", label: "Dong vietnamita (VND)" },
  { code: "TRY", symbol: "₺", label: "Lira turca (TRY)" },
  { code: "RUB", symbol: "₽", label: "Rublo russo (RUB)" },
  { code: "ZAR", symbol: "R", label: "Rand sul-africano (ZAR)" },
  { code: "AOA", symbol: "Kz", label: "Kwanza angolano (AOA)" },
  { code: "MZN", symbol: "MT", label: "Metical moçambicano (MZN)" },
  { code: "CVE", symbol: "$", label: "Escudo cabo-verdiano (CVE)" },
  { code: "NOK", symbol: "kr", label: "Coroa norueguesa (NOK)" },
  { code: "SEK", symbol: "kr", label: "Coroa sueca (SEK)" },
  { code: "DKK", symbol: "kr", label: "Coroa dinamarquesa (DKK)" },
  { code: "PLN", symbol: "zł", label: "Złoty polonês (PLN)" },
];

// País (ISO-3166 alpha-2, vindo do DDI do telefone) → moeda padrão.
// Usado só para sugerir a moeda inicial no cadastro; o usuário pode trocar.
export const COUNTRY_TO_CURRENCY = {
  BR: "BRL",
  US: "USD",
  CA: "CAD",
  AU: "AUD",
  NZ: "NZD",
  GB: "GBP",
  // Zona do euro
  PT: "EUR",
  ES: "EUR",
  FR: "EUR",
  DE: "EUR",
  IT: "EUR",
  IE: "EUR",
  NL: "EUR",
  BE: "EUR",
  AT: "EUR",
  GR: "EUR",
  FI: "EUR",
  // América Latina
  AR: "ARS",
  CL: "CLP",
  CO: "COP",
  MX: "MXN",
  PE: "PEN",
  UY: "UYU",
  PY: "PYG",
  BO: "BOB",
  VE: "VES",
  // Outros
  CH: "CHF",
  JP: "JPY",
  CN: "CNY",
  IN: "INR",
  KR: "KRW",
  VN: "VND",
  TR: "TRY",
  RU: "RUB",
  ZA: "ZAR",
  AO: "AOA",
  MZ: "MZN",
  CV: "CVE",
  NO: "NOK",
  SE: "SEK",
  DK: "DKK",
  PL: "PLN",
};
