// Anúncios de Plus/Pro no dashboard (só pra conta free). Ordem = prioridade de desempate.
// tabs: abas do dashboard onde aparece; minDays: idade mínima da conta.
export const upsellAds = [
  {
    id: "pix-automatico",
    tabs: ["menu"],
    minDays: 3,
    title: "Assine sem cartão de crédito",
    text: "Com o Pix Automático você autoriza uma vez no app do banco e pronto. Cancela quando quiser.",
    cta: "Ver planos",
    href: "/dashboard/pricing?plan=plus",
  },
  {
    id: "anual-economia",
    tabs: ["menu"],
    minDays: 10,
    title: "Plano anual: 2 meses grátis",
    text: "Plus por R$ 24,92/mês no anual. Economia de R$ 59,80 por ano.",
    cta: "Ver plano anual",
    href: "/dashboard/pricing?plan=plus&cycle=yearly",
  },
  {
    id: "plus-vitrine",
    tabs: ["menu"],
    minDays: 3,
    title: "Deixe seu cardápio mais vendedor",
    text: "Preço promocional, itens em destaque, combos e layouts em grade no Plus.",
    cta: "Conhecer o Plus",
    href: "/dashboard/pricing?plan=plus",
  },
  {
    id: "pro-cupons",
    tabs: ["menu"],
    minDays: 7,
    title: "Traga o cliente de volta",
    text: "Crie cupons de desconto pro seu cardápio com o Pro.",
    cta: "Conhecer o Pro",
    href: "/dashboard/pricing?plan=pro",
  },
  {
    id: "plus-taxa-bairro",
    tabs: ["orders"],
    minDays: 2,
    title: "Frete certo pra cada bairro",
    text: "Cobre uma taxa de entrega diferente por bairro e pare de perder dinheiro na entrega. Plus.",
    cta: "Conhecer o Plus",
    href: "/dashboard/pricing?plan=plus",
  },
  {
    id: "pro-impressao",
    tabs: ["orders"],
    minDays: 2,
    title: "Pedido impresso direto na cozinha",
    text: "Imprima cada pedido com um clique com o Pro.",
    cta: "Conhecer o Pro",
    href: "/dashboard/pricing?plan=pro",
  },
  {
    id: "pro-relatorios",
    tabs: ["sales"],
    minDays: 2,
    title: "Saiba o que mais vende",
    text: "Dashboard e relatório de vendas completos com o Pro.",
    cta: "Conhecer o Pro",
    href: "/dashboard/pricing?plan=pro",
  },
];
