export const blogPosts = [
  {
    id: 1,
    title: "Guia definitivo para criar um cardápio digital",
    date: "12 de janeiro de 2025",
    mainImage: "https://rfgkalwtrxbiqrqwxmxf.supabase.co/storage/v1/object/public/blog-images/post1/main.jpg",
    slug: "guia-definitivo-cardapio-digital",
  },
  {
    id: 2,
    title: "Os maiores benefícios do cardápio digital para restaurantes",
    date: "28 de janeiro de 2025",
    mainImage: "https://rfgkalwtrxbiqrqwxmxf.supabase.co/storage/v1/object/public/blog-images/post1/main.jpg",
    slug: "beneficios-cardapio-digital-restaurantes",
  },
  {
    id: 3,
    title: "Como um cardápio digital melhora a experiência do cliente",
    date: "10 de fevereiro de 2025",
    mainImage: "https://rfgkalwtrxbiqrqwxmxf.supabase.co/storage/v1/object/public/blog-images/post1/main.jpg",
    slug: "cardapio-digital-experiencia-cliente",
  },
  {
    id: 4,
    title: "Erros comuns ao criar um cardápio digital",
    date: "22 de fevereiro de 2025",
    mainImage: "https://rfgkalwtrxbiqrqwxmxf.supabase.co/storage/v1/object/public/blog-images/post1/main.jpg",
    slug: "erros-comuns-cardapio-digital",
  },
  {
    id: 5,
    title: "Cardápio digital vale a pena para pequenos negócios?",
    date: "5 de março de 2025",
    mainImage: "https://rfgkalwtrxbiqrqwxmxf.supabase.co/storage/v1/object/public/blog-images/post1/main.jpg",
    slug: "cardapio-digital-pequenos-negocios",
  },
  {
    id: 6,
    title: "Tendências de design para cardápios digitais em 2025",
    date: "18 de março de 2025",
    mainImage: "https://rfgkalwtrxbiqrqwxmxf.supabase.co/storage/v1/object/public/blog-images/post1/main.jpg",
    slug: "tendencias-design-cardapios-2025",
  },
  {
    id: 7,
    title: "Como criar um cardápio digital que vende mais",
    date: "2 de abril de 2025",
    mainImage: "https://rfgkalwtrxbiqrqwxmxf.supabase.co/storage/v1/object/public/blog-images/post1/main.jpg",
    slug: "cardapio-digital-que-vende-mais",
  },
  {
    id: 8,
    title: "Diferenças entre cardápio físico e digital",
    date: "15 de abril de 2025",
    mainImage: "https://rfgkalwtrxbiqrqwxmxf.supabase.co/storage/v1/object/public/blog-images/post1/main.jpg",
    slug: "diferencas-cardapio-fisico-digital",
  },
  {
    id: 9,
    title: "Cardápio digital e QR Code: como usar corretamente",
    date: "29 de abril de 2025",
    mainImage: "https://rfgkalwtrxbiqrqwxmxf.supabase.co/storage/v1/object/public/blog-images/post1/main.jpg",
    slug: "cardapio-digital-qr-code",
  },
  {
    id: 10,
    title: "Como organizar categorias em um cardápio digital",
    date: "10 de maio de 2025",
    mainImage: "https://rfgkalwtrxbiqrqwxmxf.supabase.co/storage/v1/object/public/blog-images/post1/main.jpg",
    slug: "organizar-categorias-cardapio-digital",
  },
  {
    id: 11,
    title: "Cardápio digital ajuda a reduzir custos?",
    date: "22 de maio de 2025",
    mainImage: "https://rfgkalwtrxbiqrqwxmxf.supabase.co/storage/v1/object/public/blog-images/post1/main.jpg",
    slug: "cardapio-digital-reduzir-custos",
  },
  {
    id: 12,
    title: "Boas práticas de UX para cardápios digitais",
    date: "4 de junho de 2025",
    mainImage: "https://rfgkalwtrxbiqrqwxmxf.supabase.co/storage/v1/object/public/blog-images/post1/main.jpg",
    slug: "ux-cardapios-digitais-boas-praticas",
  },
  {
    id: 13,
    title: "Como destacar pratos mais lucrativos no cardápio digital",
    date: "17 de junho de 2025",
    mainImage: "https://rfgkalwtrxbiqrqwxmxf.supabase.co/storage/v1/object/public/blog-images/post1/main.jpg",
    slug: "destacar-pratos-lucrativos-cardapio-digital",
  },
  {
    id: 14,
    title: "Cardápio digital funciona sem internet?",
    date: "1 de julho de 2025",
    mainImage: "https://rfgkalwtrxbiqrqwxmxf.supabase.co/storage/v1/object/public/blog-images/post1/main.jpg",
    slug: "cardapio-digital-sem-internet",
  },
  {
    id: 15,
    title: "Como personalizar cores e fontes no cardápio digital",
    date: "15 de julho de 2025",
    mainImage: "https://rfgkalwtrxbiqrqwxmxf.supabase.co/storage/v1/object/public/blog-images/post1/main.jpg",
    slug: "personalizar-cores-fontes-cardapio-digital",
  },
  {
    id: 16,
    title: "Cardápio digital aumenta o ticket médio?",
    date: "29 de julho de 2025",
    mainImage: "https://rfgkalwtrxbiqrqwxmxf.supabase.co/storage/v1/object/public/blog-images/post1/main.jpg",
    slug: "cardapio-digital-aumenta-ticket-medio",
  },
  {
    id: 17,
    title: "Por que restaurantes modernos adotam cardápio digital",
    date: "12 de agosto de 2025",
    mainImage: "https://rfgkalwtrxbiqrqwxmxf.supabase.co/storage/v1/object/public/blog-images/post1/main.jpg",
    slug: "restaurantes-modernos-cardapio-digital",
  },
  {
    id: 18,
    title: "Cardápio digital é seguro? Entenda os mitos",
    date: "26 de agosto de 2025",
    mainImage: "https://rfgkalwtrxbiqrqwxmxf.supabase.co/storage/v1/object/public/blog-images/post1/main.jpg",
    slug: "mitos-seguranca-cardapio-digital",
  },
  {
    id: 19,
    title: "Como atualizar preços rapidamente no cardápio digital",
    date: "9 de setembro de 2025",
    mainImage: "https://rfgkalwtrxbiqrqwxmxf.supabase.co/storage/v1/object/public/blog-images/post1/main.jpg",
    slug: "atualizar-precos-cardapio-digital",
  },
  {
    id: 20,
    title: "Cardápio digital para bares: o que muda?",
    date: "23 de setembro de 2025",
    mainImage: "https://rfgkalwtrxbiqrqwxmxf.supabase.co/storage/v1/object/public/blog-images/post1/main.jpg",
    slug: "cardapio-digital-para-bares",
  },
  {
    id: 21,
    title: "Como usar fotos de pratos no cardápio digital",
    date: "7 de outubro de 2025",
    mainImage: "https://rfgkalwtrxbiqrqwxmxf.supabase.co/storage/v1/object/public/blog-images/post1/main.jpg",
    slug: "fotos-pratos-cardapio-digital",
  },
  {
    id: 22,
    title: "Cardápio digital para delivery: vantagens reais",
    date: "14 de outubro de 2025",
    mainImage: "https://rfgkalwtrxbiqrqwxmxf.supabase.co/storage/v1/object/public/blog-images/post1/main.jpg",
    slug: "cardapio-digital-delivery-vantagens",
  },
  {
    id: 23,
    title: "Como reduzir erros de pedido com cardápio digital",
    date: "21 de outubro de 2025",
    mainImage: "https://rfgkalwtrxbiqrqwxmxf.supabase.co/storage/v1/object/public/blog-images/post1/main.jpg",
    slug: "reduzir-erros-pedido-cardapio-digital",
  },
  {
    id: 24,
    title: "Cardápio digital para cafeterias: boas práticas",
    date: "28 de outubro de 2025",
    mainImage: "https://rfgkalwtrxbiqrqwxmxf.supabase.co/storage/v1/object/public/blog-images/post1/main.jpg",
    slug: "cardapio-digital-cafeterias",
  },
  {
    id: 25,
    title: "Como testar a usabilidade do seu cardápio digital",
    date: "4 de novembro de 2025",
    mainImage: "https://rfgkalwtrxbiqrqwxmxf.supabase.co/storage/v1/object/public/blog-images/post1/main.jpg",
    slug: "testar-usabilidade-cardapio-digital",
  },
  {
    id: 26,
    title: "Cardápio digital pode substituir o garçom?",
    date: "11 de novembro de 2025",
    mainImage: "https://rfgkalwtrxbiqrqwxmxf.supabase.co/storage/v1/object/public/blog-images/post1/main.jpg",
    slug: "cardapio-digital-substitui-garcom",
  },
  {
    id: 27,
    title: "Como escalar seu restaurante com cardápio digital",
    date: "18 de novembro de 2025",
    mainImage: "https://rfgkalwtrxbiqrqwxmxf.supabase.co/storage/v1/object/public/blog-images/post1/main.jpg",
    slug: "escalar-restaurante-cardapio-digital",
  },
  {
    id: 28,
    title: "Cardápio digital para franquias: o que considerar",
    date: "25 de novembro de 2025",
    mainImage: "https://rfgkalwtrxbiqrqwxmxf.supabase.co/storage/v1/object/public/blog-images/post1/main.jpg",
    slug: "cardapio-digital-franquias",
  },
  {
    id: 29,
    title: "Como preparar seu restaurante para o cardápio digital",
    date: "2 de dezembro de 2025",
    mainImage: "https://rfgkalwtrxbiqrqwxmxf.supabase.co/storage/v1/object/public/blog-images/post1/main.jpg",
    slug: "preparar-restaurante-cardapio-digital",
  },
  {
    id: 30,
    title: "O futuro dos cardápios digitais nos restaurantes",
    date: "15 de dezembro de 2025",
    mainImage: "https://rfgkalwtrxbiqrqwxmxf.supabase.co/storage/v1/object/public/blog-images/post1/main.jpg",
    slug: "futuro-cardapios-digitais-restaurantes",
  },
];
